#### Remaining are Q6

#### numpy and Pandas Q12.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q1: Compute Product of two non-negative numbers without arithmetic operator. You are only allowed to use: bitwise operators <<, >>, |, &, ~, ^.


In [14]:
#Question1
def multiply_bitwise(multiplicand,multiplier):
    # convert the multiplier into binary number
    multiplier_binary =  bin(multiplier)
    # make an empty list called binary
    binary = []

    # put the binary numbers into list
    for j in range(2,len(multiplier_binary)):
        binary.append(multiplier_binary[j])

    #reversing the list becasue binary start multiplying from right, but looping starts from left
    binary.reverse()

    answer = 0
    final = 0

    # finding the 1s in the binary list and shifting the multiplicand according to its position in binary
    # which is the same as the count of i
    for i in range(0,len(binary)):
        if binary[i] == '1':
            answer = multiplicand<<i
            final += answer

    print("The product of " + str(multiplicand) + " and " + str(multiplier) + " is " + str(final))



multiply_bitwise(10,14)


The product of 10 and 14 is 140


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q2: Given a string check if its characters can be permuted into a palindrome, a palindrome is word that is the same forward and backward, for example “aabaa”


In [198]:
string = input("Input the word:  ")

#convert string to a set in the list
set = list(set(string))

#sorting the set of alphabets
set.sort()

# counting the occurances of alphabets
item_count = []
for i in range(0, len(set)):
	current_item_count = string.count(set[i])
	item_count.append(current_item_count)

print("The alphabets are " + str(set))
print("the count of them is " + str(item_count))

evens = []
odds = []

# putting even and odd counts of alphabets in separate lists
for i in range(0,len(item_count)):
    if item_count[i]%2 == 0:
        evens.append(item_count[i])
    else:
        odds.append(item_count[i])

print("Number of odd values are")
print(odds)

print("Number of even values are")
print(evens)

# to be palindrome, all alphabets should occur even number of times
# or odd number of times plus 1 odd number of time
if len(odds) == 0 or len(odds) == 1:
    print("It is a palindrome")
else:
    print("it is not a palindrome")


Input the word:   babaaa


The alphabets are ['a', 'b']
the count of them is [4, 2]
Number of odd values are
[]
Number of even values are
[4, 2]
It is a palindrome


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q3: Write a function to partition a list around a given value x, such that all numbers smaller than x comes before x and all numbers greater than x comes after x.  Ex. [ 3, 5, 1, 10, 4, 6, 9], x = 5 ==> [3, 1, 4, 5, 6, 9, 10]


In [1]:
my_list = [8,9,7,1,2,5,4,7,9]
x = 5


smaller_list = []
x_list = []
larger_list = []

for i in range(1,len(my_list)):
    if x > my_list[i]:
        smaller_list.append(my_list[i])
    elif x == my_list[i]:
        x_list.append(my_list[i])
    elif x < my_list[i]:
        larger_list.append(my_list[i])
final = smaller_list + x_list + larger_list
print(smaller_list)
print(x_list)
print(larger_list)
print(final)



[1, 2, 4]
[5]
[9, 7, 7, 9]
[1, 2, 4, 5, 9, 7, 7, 9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q4: Convert a real number between 0 and 1 to a binary string, if you can’t represent the number in at most 32 characters print “ERROR”


In [ ]:

o = float(input("Type a number between 1 to 0: "))
def Binary(o):
	if (o >= 1 or o <= 0):
    	return "I asked for number between 1 to 0, try again!"
	string = "."   
	while (o > 0):
    	if(len(string) >= 32):
        	return "ERROR"

    	b = o * 2
    	if (b >= 1):

        	string = string + "1"
        	o = b -1
    	else:
        	string = string + "0"
        	o = b
	return string
answer = Binary(o)
if answer == "ERROR":
	print("ERROR")
elif answer == "I asked for number between 1 to 0, try again!":
	print("I asked for number between 1 to 0, try again!")
else:
	print("0"+ answer)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q5: Write a method that returns all subset of a set of numbers, don’t use builtin functions.


In [ ]:

request = list(input("Hello, please give me more than one denary type numbers: "))

def sub_func (a):
	sets = []
	lists = [sets]
	for i in range(len(a)):
    	x = lists[:]
    	y = a[i]
    	if y == " ":
        	k = y.split(" ")
    	else:
        	for b in range(len(lists)):
            	lists[b] = lists[b] + [y]
        	lists = x + lists
   	 
	return lists
    
print(sub_func(request))


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q6: A magic index in an array A is an index x such that A[x] = x, 
#### given a SORTED array A find a magic index.


In [4]:
# This is the answer
import numpy as np

random_list = [-1,0,1,2,4,9]

for i in range(0,len(random_list)):
    
    if random_list[i] == i:
        print("magic index is " + str(random_list[i]))
        
    


magic index is 4


In [3]:
## basic initial code
import numpy as np

random_list = [-1,0,1,2,4,9]
magic_array = np.arange(len(random_list) + 1)

for i in range(0,len(random_list)):
    
    if random_list[i] == magic_array[i]:
        print("magic index is " + str(random_list[i]))
        
    elif random_list[i] != magic_array[i]:
        continue




magic index is 4


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q7: Given two sorted arrays  A and B, merge into a single array: A[3, 7, 10], B=[1, 2, 4, 5, 6, 9, 11] ==> [1,2,3,5,6,7,9,10,11]


In [11]:
import numpy as np
arr_a = np.array((1, 3, 2, 5, 6))
arr_b = np.array((7, 6, 8, 9, 10))

arr_c = np.concatenate((arr_a, arr_b), axis =0)
print(np.sort(arr_c))




[ 1  2  3  5  6  6  7  8  9 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q8: Schedule Tasks to minimise the waiting time. Given a list of service time for tasks, find the best scheduling to minimise the waiting time. For example given service time [2, 5, 1, 3], if we schedule them in the given order the waiting time = 0 + (2) + (2 +5) + (2 +5 +1) = 17, if we schedule them in order of decreasing service, the waiting time = 0 + (5) + (5+3) + (5+3 +2) = 23. The best scheduling in this case is [1, 2, 3, 5]


In [13]:
waiting_time = [5,2,3,1]
waiting_time.sort()
print(waiting_time)


[1, 2, 3, 5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q9: Write function integers_in_brackets that finds from a given string all integers that are enclosed in brackets.
Example run: integers_in_brackets("  afd [asd] [12 ] [a34]  [ -43 ]tt [+12]xxx") returns [12, -43, 12]. So there can be whitespace between the number and the brackets, but no other character besides those that make up the integer. Use regular expressions to do this.



In [19]:
import re

getInput = input("Please provide inputs: ")
grab = getInput

conditions = r"(?:\[(\s*?[-+]?\d+\s*?)\])"
                                                                                            	 
answer = list(map(eval, re.findall(conditions, grab)))

print(answer)

# Receive input
# Save input as another variable
# Create Regex and have it saved as variable, to clean up code
# Condition variable include:
# Non-capturing group to capture string within group
# Greedy match - capture more one string, good for more than 1 digit integer and so on
# Using \ for [ and ] allow them not to be escaped
# After that, we create answer that include our condition and user input variable
# we also made sure to use list, map and eval for this to convert to list, make it iterable and execute expression
# Finally, we print our answer


Please provide inputs:  (" afd [asd] [12 ] [a34] [ -43 ]tt [+12]xxx")


[12, -43, 12]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)


#### Q10: Create a function called summary that gets a list of filenames as a parameter. 

#### The input files should contain a floating point number on each line of the file. Make your function read these numbers and then return a triple containing the sum, average, and standard deviation of these numbers for the file. 

https://en.wikipedia.org/wiki/Standard_deviation#Sample_standard_deviation_of_metabolic_rate_of_northern_fulmars 

#### The main function should call the function summary for each filename in the list sys.argv[1:] of command line parameters. (Skip sys.argv[0] since it contains the name of the current program.)

##### Example of usage from the command line: python3 src/summary.py src/example.txt src/example2.txt
##### Print floating point numbers using six decimals precision. The output should look like this:
##### File: src/example.txt Sum: 51.400000 Average: 10.280000 Stddev: 8.904606
##### File: src/example2.txt Sum: 5446.200000 Average: 1815.400000 Stddev: 3124.294045



In [ ]:
# the answer to part 1 is here:-


# link for help https://www.tutorialspoint.com/python/python_command_line_arguments.htm
#print( 'Number of arguments:', len(sys.argv), 'arguments.')
#print( 'Argument List:', str(sys.argv))


import sys

from math import sqrt

def summary(text_file):

## iterating over the arguments of command line inputs given by user to open files
## the argument itself is sys.argv and range from 1 as according to format; first argument in
## command prompt is the name of file

    for i in range(1,len(sys.argv)):

        # open the text file name as read only
        text_file = open(sys.argv[i], "r")

        # create variable lines from the content of the lines of text file
        lines = text_file.readlines()

        # creating the integars 
        for t in range(len(lines)):
            lines[t] = int(lines[t])

        # sum and average    
        file_sum = sum(lines)
        file_average = file_sum / len(lines)

        # Standard deviation
        SUMM = 0
        for j in lines:
            SUMM += (j - file_average) ** 2

        stdev = sqrt(SUMM / (len(lines) - 1))

        # printing the outpur
        print("File: " + str(sys.argv[i]) + " Sum: " + str(file_sum) + " Average: " + str(file_average) + " Stddev: "+ str(stdev))

summary("text_file")




#### Part 2.
#### If some line doesn’t represent a number, you can just ignore that line. 
#### You can achieve this with the try-except block. 
####  An example of recovering from an exceptional situation:

#### try: 
##### x = float(line)           # The float constructor raises ValueError exception if conversion is no possible
##### except ValueError:
##### # Statements in here are executed when the above conversion fails


In [ ]:

import sys

from math import sqrt

def summary(text_file):

## iterating over the arguments of command line inputs given by user to open files
## the argument itself is sys.argv and range from 1 as according to format; first argument in
## command prompt is the name of file

    for i in range(1,len(sys.argv)):

        text_file = open(sys.argv[i], "r")

        lines = text_file.readlines()
        # defining a list where only floats will go    
        list_floats = []

        # looping over the range of lines, and putting only floats in list_floats
        # if it is not float, except will pass and the loop will go to next value of list 'lines'
        
        for t in range(len(lines)):

            try:
               lines[t] = float(lines[t])
               list_floats.append(lines[t])

            except ValueError:
                pass

        # sum and average    

        file_sum = sum(list_floats)
        file_average = file_sum / len(list_floats)

        # Standard deviation

        SUMM = 0
        for j in list_floats:
            SUMM += (j - file_average) ** 2

        stdev = sqrt(SUMM / (len(list_floats) - 1))

        print("File: " + str(sys.argv[i]) + " Sum: " + str(file_sum) + " Average: " + str(file_average) + " Stddev: "+ str(stdev))

summary("text_file")



![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q11: Write a function extract_numbers that gets a string as a parameter. It should return a list of numbers that can be both ints and floats. 

#### Split the string to words at whitespace using the split() method. Then iterate through each word, and initially try to convert to an int. If unsuccesful, then try to convert to a float. If not a number then skip the word.

	Example run: print(extract_numbers("abd 123 1.2 test 13.2 -1")) will return [123, 1.2, 13.2, -1]



In [44]:

mystring = " abd 123 1.2 test 13.2 -1"
sss = mystring.split()
blist = []


for i in range(len(sss)):
    try:
        sss[i] = float(sss[i])
        blist.append(sss[i])
        
        if type(sss[i]) != float:
            sss[i] = int(sss[i])
            blist.append(sss[i])

    except ValueError:
        pass
    
        
print('the original list was ' + str(sss))
print()
print('Only numbers list is ' + str(blist))


        

the original list was ['abd', 123.0, 1.2, 'test', 13.2, -1.0]

Only numbers list is [123.0, 1.2, 13.2, -1.0]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Numpy and Pandas Section

#### Q12: Write function vector_lengths that gets a two dimensional array of shape (n,m) as a parameter. 

##### Each row in this array corresponds to a vector. 
##### The function should return an array of shape (n,), that has the length of each vector in the input. 

##### The length is defined by the usual Euclidean norm. 

##### Don’t use loops at all in your solution. Instead use vectorized operations. 
##### You must use at least the np.sum and the np.sqrt functions. 

##### You can’t use the function scipy.linalg.norm. Test your function in the main function.


In [20]:
def euclidean_norm(all_numb,rows,columns):
    np_array_2d = np.arange(all_numb).reshape([rows,columns])
          
    # distance is sqrt of ( sq of 1st element + sq of 2nd element + sq of 3rd element ...)
    total_squares = np.square(np_array_2d)
    sumofsquares = total_squares.sum(axis=1)

    print("sum of the squares of each row is")
    print(sumofsquares)

    sqrt_sumofsquares = np.sqrt(sumofsquares)
    print("the Euclidean norm is")
    print(sqrt_sumofsquares)
    
     
euclidean_norm(15,3,5)    

sum of the squares of each row is
[ 30 255 730]
the Euclidean norm is
[ 5.47722558 15.96871942 27.01851217]


In [ ]:
# these are all practice runs, please ignore it !!

np_array_2d = np.arange(15).reshape([3,5])
print("array is")
print(np_array_2d)

square_root =np.sqrt(np_array_2d)
print("square root of whole array values are")
print(square_root)

total_sum = np.sum(np_array_2d)
print("total sum of all values in array is")
print(total_sum)

# product of rows
total_product = np_array_2d.prod(axis=1)
print("total product of rows are")
print(total_product)

# squares of all values in array
total_squares = np.square(np_array_2d)
print("squares of each value of the array is")
print(total_squares)

# sum of each rows in the array
total_sum = np_array_2d.sum(axis=1)
print("sum of each rows of the array is")
print(total_sum)


# distance is sqrt of ( sq of 1st element + sq of 2nd element + sq of 3rd element ...)
total_squares = np.square(np_array_2d)
sumofsquares = total_squares.sum(axis=1)

print("sum of the squares of each row is")
print(sumofsquares)

sqrt_sumofsquares = np.sqrt(sumofsquares)
print("the Euclidean norm is")
print(sqrt_sumofsquares)



![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q13: Write function multiplication_table that gets a positive integer n as parameter. 

#### The function should return an array with shape (n,n). The element at index (i,j) should be i*j. 

#### Don’t use for loops! 

#### In your solution, rely on broadcasting, the np.arange function, reshaping and vectorized operators. Example of usage:

print(multiplication_table(4))

[[0 0 0 0]

[0 1 2 3]

[0 2 4 6]

[0 3 6 9]]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### This is just Rough Work 

In [134]:
# https://realpython.com/lessons/numpy-arange-overview/

# numpy.arange([start,]stop, [step,],dtype=None)
# numpy.ndarray

import numpy as np

a = np.arange(start=1, stop=10, step=1)
print(a)
b = np.arange(1,10,2)
print(b)

c = np.arange


    

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [163]:
mm = 4
a = numpy.zeros(shape=(mm,mm))

i = 1
while i < 4:
    a[i] = a[i-1] + [0,1,2,3]
    if i == (mm-1):
        break
    i += 1
    
print(a)


[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [154]:
j = 7
y = np.arange(j**2).reshape(j,j)


print(y)



[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [158]:
y[:, 0] =  1
print(y)

[[ 1  1  2  3  4  5  6]
 [ 1  8  9 10 11 12 13]
 [ 1 15 16 17 18 19 20]
 [ 1 22 23 24 25 26 27]
 [ 1 29 30 31 32 33 34]
 [ 1 36 37 38 39 40 41]
 [ 1 43 44 45 46 47 48]]


In [177]:
np.arange(6).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [190]:
np.zeros((1,6))

array([[0., 0., 0., 0., 0., 0.]])

In [191]:

bbb = np.arange(6).reshape(-1,1) + np.zeros((1,6))
#ccc = bbb + np.zeros((6,1))

print(bbb)
#print(ccc)


[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]]


In [171]:
np.arange(1,13).reshape(-1,1) * np.arange(1,13)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

In [196]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [194]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [203]:
abc=np.zeros((1,4)) + np.zeros((4,1))

print(abc)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [209]:
x = np.arange(0,4,1)
print(x)

[0 1 2 3]


In [212]:
y = x * abc
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Answer starts from here :-

In [225]:
allrows = np.arange(4).reshape(-1,1) + np.zeros((1,4))

print(allrows)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [221]:
allcol = np.arange(4) + np.zeros((4,1))

print(allcol)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [223]:
final = allrows * allcol

print(final)

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]
 [0. 3. 6. 9.]]


In [224]:

def multiplication_table(some):
    allrows = np.arange(some).reshape(-1,1) + np.zeros((1,some))
    allcol = np.arange(some) + np.zeros((some,1))
    final = allrows * allcol
    
    return final

multiplication_table(4)

    


array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q14: Load the iris dataset, https://gist.github.com/netj/8836201, using pd.read_csv(). The four columns of the returned array correspond to

sepal length (cm)

sepal width (cm)

petal length (cm)

petal width (cm)

#### Part 1. What is the Pearson correlation between the variables sepal length and petal length. Compute this using the scipy.stats.pearsonr function. It returns a 	tuple whose first element is the correlation. Write a function lengths that loads the data and returns the correlation.

#### Part 2. What are the correlations between all the variables. Write a function correlations that returns an array of shape (4,4) containing the correlations. Use 	the function np.corrcoef. Which pair of variables is the most highly correlated?

Note the input formats of both functions pearsonr and corrcoef.


In [2]:
df_i = pd.read_csv (r'D:\jupyter\python_competition\questions\iris.csv')

In [7]:
# to see how many unique variety are there
df_i.variety.unique()


array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [17]:
# create a new dataframe with two columns and drop missing values

new_df_i = df_i[['sepal.length','petal.length']].dropna()

new_df_i.head()


sepal.length  petal.length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

--------------------------------------------------------------------------------------------------------------------------------
##### As a rule of thumb sizes from Rea and Parker (2014):

|\|r\|| Interpretation|
|-------|---------------|
|0.00 < 0.10| Negligible|
|0.10 < 0.20 |Weak|
|0.20 < 0.40| Moderate|
|0.40 < 0.60| Relatively strong|
|0.60 < 0.80| Strong|
|0.80 <= 1.00| Very strong|



In [18]:
# using pandas corelation coefficient function to see the correlation

new_df_i.corr()


sepal.length  petal.length
sepal.length      1.000000      0.871754
petal.length      0.871754      1.000000

In [36]:
from scipy.stats import pearsonr

In [24]:

pearsonr(new_df_i['sepal.length'],new_df_i['petal.length'])

(0.8717537758865832, 1.0386674194497525e-47)

The first value is the correlation coefficient and the second is p value (significance)

#### Part 2. What are the correlations between all the variables. Write a function correlations that returns an array of shape (4,4) containing the correlations. Use 	the function np.corrcoef. Which pair of variables is the most highly correlated?


In [31]:
array_sepal_l = np.array(df_i['sepal.length'])
array_sepal_w = np.array(df_i['sepal.width'])
array_petal_l = np.array(df_i['petal.length'])
array_petal_w = np.array(df_i['petal.width'])

In [32]:
df_i.corr()

sepal.length  sepal.width  petal.length  petal.width
sepal.length      1.000000    -0.117570      0.871754     0.817941
sepal.width      -0.117570     1.000000     -0.428440    -0.366126
petal.length      0.871754    -0.428440      1.000000     0.962865
petal.width       0.817941    -0.366126      0.962865     1.000000

In [33]:
np.corrcoef(array_petal_l, array_sepal_l)

array([[1.        , 0.87175378],
       [0.87175378, 1.        ]])

In [34]:
np.corrcoef(array_petal_w, array_petal_l)

array([[1.        , 0.96286543],
       [0.96286543, 1.        ]])

##### Ans: There is a strong correlation of 0.87 between petal length and sepal length. There is also a strong correlation of 0.96 between petal width and petal length 

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Q15: Make function powers_of_series that takes a Series and a positive integer k as parameters and returns a DataFrame. 

#### The resulting DataFrame should have the same index as the input Series. 

#### The first column of the dataFrame should be the input Series, 
#### The second column should contain the Series raised to power of two. 
#### The third column should contain the Series raised to the power of three, and so on until (and including) power of k. The columns should have indices from 1 to k.

#### The values should be numbers, but the index can have any type. 

#### Test your function from the main function. Example of usage:

	s = pd.Series([1,2,3,4], index=list("abcd"))
    
	print(powers_of_series(s, 3))
    
	Should print:
    
	   1   2   3
	a  1   1   1
	b  2   4   8
	c  3   9  27


In [99]:
import pandas as pd

s = pd.Series([1,2,3,4], index = list("abcd"))

print(s)

a    1
b    2
c    3
d    4
dtype: int64


In [123]:
df_s = s.to_frame('1')
df_s

1
a  1
b  2
c  3
d  4

In [122]:
df_s['2'] = df_s['1'] ** 2
df_s['3'] = df_s['1'] ** 3

df_s

1   2   3
a  1   1   1
b  2   4   8
c  3   9  27
d  4  16  64

In [127]:
import pandas as pd

def powerseries(t,j):
    df_try = t.to_frame('1')
    
    #j = 5

    for i in range(2,j):
        df_try[i] = df_try['1'] ** i
    
    return df_try
    
t = pd.Series([1,2,3,4], index=list("abcd"))
print(powerseries(t,5))


   1   2   3    4
a  1   1   1    1
b  2   4   8   16
c  3   9  27   81
d  4  16  64  256


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## THE END OF PART 1